### ISSUE TITLE
Disable bootstrap in diff-lcs

### ISSUE THREAD

**Issue by domcleal** [domcleal/sclo-ror42#2]
diff-lcs has bootstrap enabled.  It fails with:

```
Failures:
  1) Diff::LCS::Hunk should be able to produce a unified diff from the two pieces
     Failure/Error: let(:hunk)     { Diff::LCS::Hunk.new(old_data, new_data, pieces[0], 3, 0) }
     NameError:
       uninitialized constant Diff::LCS::Hunk
     # ./spec/hunk_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ./spec/hunk_spec.rb:23:in `block (2 levels) in <top (required)>'
  2) Diff::LCS::Hunk should be able to produce a context diff from the two pieces
     Failure/Error: let(:hunk)     { Diff::LCS::Hunk.new(old_data, new_data, pieces[0], 3, 0) }
     NameError:
       uninitialized constant Diff::LCS::Hunk
     # ./spec/hunk_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ./spec/hunk_spec.rb:35:in `block (2 levels) in <top (required)>'
  3) Diff::LCS::Hunk should be able to produce an old diff from the two pieces
     Failure/Error: let(:hunk)     { Diff::LCS::Hunk.new(old_data, new_data, pieces[0], 3, 0) }
     NameError:
       uninitialized constant Diff::LCS::Hunk
     # ./spec/hunk_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ./spec/hunk_spec.rb:46:in `block (2 levels) in <top (required)>'
  4) Diff::LCS::Hunk should be able to produce a reverse ed diff from the two pieces
     Failure/Error: let(:hunk)     { Diff::LCS::Hunk.new(old_data, new_data, pieces[0], 3, 0) }
     NameError:
       uninitialized constant Diff::LCS::Hunk
     # ./spec/hunk_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ./spec/hunk_spec.rb:56:in `block (2 levels) in <top (required)>'
  5) Diff::LCS::Hunk with empty first data set should be able to produce a unified diff
     Failure/Error: let(:hunk)     { Diff::LCS::Hunk.new(old_data, new_data, pieces[0], 3, 0) }
     NameError:
       uninitialized constant Diff::LCS::Hunk
     # ./spec/hunk_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ./spec/hunk_spec.rb:67:in `block (3 levels) in <top (required)>'
```

**Comment by domcleal** [comment]
Working, perhaps due to using rspec 3.x originally.
